name: skysat_stereo
channels:
 - conda-forge
dependencies:
 # core data science 
 - python
 - scipy
 - numpy
 - pandas
 - matplotlib
 # geospatial (raster+vector)
 - gdal
 - rasterio
 - geopandas
 - pygeos
 - shapely
 - contextily
 - descartes
 # misc
 - pip
 - psutil
 - pip:
   # rotation_matrices
   - pyquaternion
   # misc
   - p_tqdm
   # geospatial+plotting
   - "--editable=git+https://github.com/dshean/pygeotools.git#egg=pygeotools"
   - "--editable=git+https://github.com/dshean/demcoreg.git#egg=demcoreg"
   - "--editable=git+https://github.com/ShashankBice/imview.git@isprs_version#egg=imview"
   - "--editable=git+https://github.com/cmla/rpcm.git#egg=rpcm"
   # review and add bare
